name: Get Feed

on:
  schedule:
    - cron: '30 12 * * *' # Runs daily at 12:30 UTC
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      RUN_FREQUENCY: 86400 # in seconds
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Updated to latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Updated to latest version
        with:
          node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@v3 # Updated to latest version
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Update Notion Feed
        run: |
          curl -o index.js https://raw.githubusercontent.com/ravgeetdhillon/notion-feeder/build/dist/index.js
          node index.js
